server:
  port: 8081

spring:
  application:
    name: judge-server

# 判题配置
judge:
  docker-host: unix:///var/run/docker.sock
  default-time-limit: 1000
  default-memory-limit: 262144
  work-dir: D:/temp/ylwy-judge
  enable-docker: false
  cpp-compile-cmd: g++ -std=c++17 -O2 -o Main Main.cpp
  java-compile-cmd: javac Main.java
  python-run-cmd: python3 Main.py

# 日志配置
logging:
  level:
    com.ylwy.judge: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
